using Microsoft.Azure.Cosmos.Table;

namespace ABU.Portfolio.Services.Abstractions;

public interface ITableStorageService
{
    Task<ITableEntity?> DeleteAsync(string tableName, ITableEntity entity, CancellationToken ct = default);
    Task<ITableEntity?> InsertOrMergeAsync(string tableName, ITableEntity entity, CancellationToken ct = default);

    /// <summary>
    /// Note that id must be generated by the consumer of this API. Partition key is used to group
    /// similar entities together and should be the same column every time. 
    /// </summary>
    /// <param name="tableName"></param>
    /// <param name="id"></param>
    /// <param name="partitionKey"></param>
    /// <param name="ct"></param>
    /// <returns></returns>
    Task<ITableEntity?> RetrieveAsync(string tableName, string id, string partitionKey, CancellationToken ct = default);
}