namespace ABU.Portfolio.Services.Abstractions;

public interface ITableStorageService
{
    Task<TEntity> DeleteAsync<TEntity>(string table, TEntity entity, CancellationToken ct = default) where TEntity : class;
    Task<TEntity> InsertOrMergeAsync<TEntity>(string table, TEntity entity, CancellationToken ct = default) where TEntity : class;
    /// <summary>
    /// Note that id must be generated by the consumer of this API. Partition key is used to group
    /// similar entities together and should be the same column every time. 
    /// </summary>
    /// <param name="table"></param>
    /// <param name="id"></param>
    /// <param name="partitionKey"></param>
    /// <param name="ct"></param>
    /// <typeparam name="TEntity"></typeparam>
    /// <returns></returns>
    Task<TEntity> RetrieveAsync<TEntity>(string table, string id, string partitionKey, CancellationToken ct = default) where TEntity : class;
}