name: Docker Image CI

on:
  push:
    branches: [ main ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_IMAGE }}
    - name: Push to Dockerhub
      run: docker push ${{ secrets.DOCKER_IMAGE }}
